//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante1
    {
        public int id_estudiante { get; set; }
        public string name { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string cargo { get; set; }
    }
}
