//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas1
    {
        public int id_notas { get; set; }
        public int id_estudiante { get; set; }
        public int id_asignatura { get; set; }
        public string nombre_asignatura { get; set; }
        public Nullable<decimal> nota1 { get; set; }
        public Nullable<decimal> nota2 { get; set; }
        public Nullable<decimal> nota3 { get; set; }
        public Nullable<decimal> definitiva { get; set; }
    }
}
